### ISSUE TITLE
how can I implement assigning of coach and seat ,if available, to a passenger ?

### ISSUE THREAD

**Issue by Sanskary2303** [AerialRobotics-IITK/Induction_Y22#12]

**Comment by pulak-gautam** [comment]
To implement assigning of coach and seat, and availability you may:- 
1. Make a set of booked seats, and assign seats to passengers randomly (over some set of seats, say 8 coaches -> A-H and 30 seats per coach. Check if the randomly assigned seat is in the set, if not assign it, else pull up another random allotment and so on.
2. Iterate from start of the train (say coach A, seat 1) to end of the train(say coach B, seat 30 -> last seat), whilst keeping of track where u r right now.
3. or, any other method that strikes you.

The idea is that implementation of this is very open ended. I agree there is some ambiguity in the problem statement here.
